### ISSUE TITLE
Render into IO

### ISSUE THREAD

**Issue by vladfaust** [epoch/tallboy#1]
Hello,

Currently tallboy can only render into new `String`. How about rendering into IO?

**Comment by epoch** [comment]
Hi, are you referring to more generic IO objects like `IO:Memory`? I found several things deprecated last time I looked into it. What is the use case you had in mind?

**Comment by vladfaust** [comment]
I'm referring to the base [`IO`](https://crystal-lang.org/api/0.27.2/IO.html), which is essentially **I**nput/**O**utput. It does not have to be `IO::Memory`. I'd like Tallboy to print its tables into `io` apart from building a `String` object.

My use-case is implementing custom `inspect(io)` for a class.

I patched Tallboy on my machine adding a `render(IO)` method, but it's kinda dirty. I could propose a PR, but it would change more API than just rendering to an IO. That's because your current code is hardly changeable, IMO. The styling logic with Symbols is obsolete, for example, as we now have autocasting.

**Comment by epoch** [comment]
I agree about styling it kind of sucks right now that's the part I want to change the most. I only found out about autocasting after straight-shoota pointed it out on reddit and I'm picking up the syntax and features of Crystal along the way. Did you find out symbols are going to be removed? I already updated alignments to use autocasting and would prefer enums over symbols.

Rendering to IO sounds good I had `to_s(io)` initially but I wasn't sure it's the right convention at that time so I took it out. Writing to IO is mainly for performance correct?

**Comment by vladfaust** [comment]
Unfortunately, the core team is very lean about symbols. I'd love to see them removed as well, but no progress such yet. However, autocasting works nicely in many cases.

> I wasn't sure it's the right convention at that time 

Having an IO-based architecture is always right in libraries which... Do output :smile: 

> Writing to IO is mainly for performance

Apart from performance it allows to properly incorporate your code into existing IO-based outputs. As I've mentioned above, `inspect` relies on IO. And `inspect` is called every time you do `pp`!

**Comment by epoch** [comment]
added 3a29408415645520ea69dd138df2058c1503e1d8
