### ISSUE TITLE
Using text colour increases column size

### ISSUE THREAD

**Issue by OisinA** [epoch/tallboy#10]
<img width="229" alt="Screen Shot 2020-08-04 at 19 39 41" src="https://user-images.githubusercontent.com/5531384/89331823-4e8e4900-d68a-11ea-8d21-5c110d5c1c62.png">
<img width="317" alt="Screen Shot 2020-08-04 at 19 39 16" src="https://user-images.githubusercontent.com/5531384/89331830-50f0a300-d68a-11ea-9ae3-f179fd16417d.png">

Adding a color to text causes the column size to change.

```
table = Tallboy.table do
            columns(true) do
                add "Title"
                add "Start"
                add "Due"
            end
            rows [
		["test", "today", "tomorrow".colorize(:red)]
	    ]
end
```

**Comment by epoch** [comment]
Yeah this is definitely not desirable. It is because colorize strings contains escape characters which we can't see but are actually bigger in size. May be I can tweak the min width calculation otherwise I'll have to look into using generics for value types

**Comment by epoch** [comment]
The patch was easy enough. see 1f03cd77d
 
Although I feel in the long term having support for colors in the library API itself will be more ideal because I can handle it much later when we render

**Comment by marghidanu** [comment]
Any news on a new version for this package?

**Comment by epoch** [comment]
pushed a new version that includes this patch
