### ISSUE TITLE
Unicode column borders

### ISSUE THREAD

**Issue by vladfaust** [epoch/tallboy#2]
Currently `puts table.render(:unicode, row_separator: true)` prints such a table:

```
┌───┬───┬───┐
│ 1 │ 2 │ 3 │
│───┴───┴───│
│ 1 │ 2 │ 3 │
│───┴───┴───│
│ 1 │ 2 │ 3 │
└───┴───┴───┘
```

Of course, that's a matter of preference, but I'd like to see full-height column borders:

```
┌───┬───┬───┐
│ 1 │ 2 │ 3 │
│───┼───┼───│
│ 1 │ 2 │ 3 │
│───┼───┼───│
│ 1 │ 2 │ 3 │
└───┴───┴───┘
```

**Comment by epoch** [comment]
fixed 3a29408415645520ea69dd138df2058c1503e1d8
